### ISSUE TITLE
no protein in the result of Normalizer

### ISSUE THREAD

**Issue by vasvale** [mutalyzer/website#23]
input NC_000011.9:g.47364696_47364697insACC  gives no protein result

**Comment by vasvale** [comment]
should it be 
NC_000011.9(MYBPC3_i001):p.(Lys409_Tyr410insVal)


?

**Comment by jfjlaros** [comment]
That is correct. Since no transcript is selected, no protein prediction is given. Mutalyzer does however suggest one equivalent description relative to a transcript: [NC_000011.9(NM_000256.3):c.1227_1228insGTG](https://mutalyzer.nl/normalizer/NC_000011.9(NM_000256.3):c.1227_1228insGTG).

In this particular case though, the insertion interferes with a splice site, so no prediction is given.

**Comment by vasvale** [comment]
it's a potential splice site interference since the ASS is preserved, should Mutalyzer give a protein output perhaps with a warning?

**Comment by jfjlaros** [comment]
I think the best option would be to run a splice site predictor in those cases. For now Mutalyzer is trying to be cautious. In many cases no answer is better than a wrong or uncertain answer.
